// Generated by gencpp from file raspicam_node/LaneDetection.msg
// DO NOT EDIT!


#ifndef RASPICAM_NODE_MESSAGE_LANEDETECTION_H
#define RASPICAM_NODE_MESSAGE_LANEDETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/CompressedImage.h>

namespace raspicam_node
{
template <class ContainerAllocator>
struct LaneDetection_
{
  typedef LaneDetection_<ContainerAllocator> Type;

  LaneDetection_()
    : steering_error(0.0)
    , at_curve(false)
    , resized_img()
    , bw_img()  {
    }
  LaneDetection_(const ContainerAllocator& _alloc)
    : steering_error(0.0)
    , at_curve(false)
    , resized_img(_alloc)
    , bw_img(_alloc)  {
  (void)_alloc;
    }



   typedef double _steering_error_type;
  _steering_error_type steering_error;

   typedef uint8_t _at_curve_type;
  _at_curve_type at_curve;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _resized_img_type;
  _resized_img_type resized_img;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _bw_img_type;
  _bw_img_type bw_img;





  typedef boost::shared_ptr< ::raspicam_node::LaneDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspicam_node::LaneDetection_<ContainerAllocator> const> ConstPtr;

}; // struct LaneDetection_

typedef ::raspicam_node::LaneDetection_<std::allocator<void> > LaneDetection;

typedef boost::shared_ptr< ::raspicam_node::LaneDetection > LaneDetectionPtr;
typedef boost::shared_ptr< ::raspicam_node::LaneDetection const> LaneDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspicam_node::LaneDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspicam_node::LaneDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace raspicam_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'raspicam_node': ['/home/corvin/catkin_ws/src/raspicam_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::raspicam_node::LaneDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspicam_node::LaneDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspicam_node::LaneDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspicam_node::LaneDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspicam_node::LaneDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspicam_node::LaneDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspicam_node::LaneDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33f171634fb931d1dc01a255358d5654";
  }

  static const char* value(const ::raspicam_node::LaneDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33f171634fb931d1ULL;
  static const uint64_t static_value2 = 0xdc01a255358d5654ULL;
};

template<class ContainerAllocator>
struct DataType< ::raspicam_node::LaneDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspicam_node/LaneDetection";
  }

  static const char* value(const ::raspicam_node::LaneDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspicam_node::LaneDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The steering angle error returned by the lane detection\n\
float64 steering_error\n\
\n\
# Whether the vehicle is at a curve or on a straight lane\n\
bool at_curve\n\
\n\
# img msg for review\n\
sensor_msgs/CompressedImage resized_img\n\
sensor_msgs/CompressedImage bw_img\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/CompressedImage\n\
# This message contains a compressed image\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
\n\
string format        # Specifies the format of the data\n\
                     #   Acceptable values:\n\
                     #     jpeg, png\n\
uint8[] data         # Compressed image buffer\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::raspicam_node::LaneDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspicam_node::LaneDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering_error);
      stream.next(m.at_curve);
      stream.next(m.resized_img);
      stream.next(m.bw_img);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspicam_node::LaneDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspicam_node::LaneDetection_<ContainerAllocator>& v)
  {
    s << indent << "steering_error: ";
    Printer<double>::stream(s, indent + "  ", v.steering_error);
    s << indent << "at_curve: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.at_curve);
    s << indent << "resized_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.resized_img);
    s << indent << "bw_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.bw_img);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPICAM_NODE_MESSAGE_LANEDETECTION_H
