// Generated by gencpp from file raspicam_node/Parking.msg
// DO NOT EDIT!


#ifndef RASPICAM_NODE_MESSAGE_PARKING_H
#define RASPICAM_NODE_MESSAGE_PARKING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace raspicam_node
{
template <class ContainerAllocator>
struct Parking_
{
  typedef Parking_<ContainerAllocator> Type;

  Parking_()
    : header()
    , steering_error(0.0)
    , parking_stg1_steering_error(0.0)
    , parking_stg2_steering_error(0.0)
    , begin_parking(false)
    , parking_stg1_stop(false)
    , parking_stg2_stop(false)  {
    }
  Parking_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steering_error(0.0)
    , parking_stg1_steering_error(0.0)
    , parking_stg2_steering_error(0.0)
    , begin_parking(false)
    , parking_stg1_stop(false)
    , parking_stg2_stop(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _steering_error_type;
  _steering_error_type steering_error;

   typedef double _parking_stg1_steering_error_type;
  _parking_stg1_steering_error_type parking_stg1_steering_error;

   typedef double _parking_stg2_steering_error_type;
  _parking_stg2_steering_error_type parking_stg2_steering_error;

   typedef uint8_t _begin_parking_type;
  _begin_parking_type begin_parking;

   typedef uint8_t _parking_stg1_stop_type;
  _parking_stg1_stop_type parking_stg1_stop;

   typedef uint8_t _parking_stg2_stop_type;
  _parking_stg2_stop_type parking_stg2_stop;





  typedef boost::shared_ptr< ::raspicam_node::Parking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspicam_node::Parking_<ContainerAllocator> const> ConstPtr;

}; // struct Parking_

typedef ::raspicam_node::Parking_<std::allocator<void> > Parking;

typedef boost::shared_ptr< ::raspicam_node::Parking > ParkingPtr;
typedef boost::shared_ptr< ::raspicam_node::Parking const> ParkingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspicam_node::Parking_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspicam_node::Parking_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace raspicam_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'raspicam_node': ['/home/corvin/catkin_ws/src/raspicam_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::raspicam_node::Parking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspicam_node::Parking_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspicam_node::Parking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspicam_node::Parking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspicam_node::Parking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspicam_node::Parking_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspicam_node::Parking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed391e1436c52e7f07926b152c4f1a22";
  }

  static const char* value(const ::raspicam_node::Parking_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed391e1436c52e7fULL;
  static const uint64_t static_value2 = 0x07926b152c4f1a22ULL;
};

template<class ContainerAllocator>
struct DataType< ::raspicam_node::Parking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspicam_node/Parking";
  }

  static const char* value(const ::raspicam_node::Parking_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspicam_node::Parking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message header\n\
Header header\n\
\n\
\n\
# Numerical variables\n\
float64 steering_error    # The steering angle error for lane keeping\n\
float64 parking_stg1_steering_error\n\
float64 parking_stg2_steering_error\n\
\n\
\n\
# Bool signals \n\
bool begin_parking        # begin parking (J-shape)\n\
bool parking_stg1_stop\n\
bool parking_stg2_stop\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::raspicam_node::Parking_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspicam_node::Parking_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steering_error);
      stream.next(m.parking_stg1_steering_error);
      stream.next(m.parking_stg2_steering_error);
      stream.next(m.begin_parking);
      stream.next(m.parking_stg1_stop);
      stream.next(m.parking_stg2_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Parking_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspicam_node::Parking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspicam_node::Parking_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steering_error: ";
    Printer<double>::stream(s, indent + "  ", v.steering_error);
    s << indent << "parking_stg1_steering_error: ";
    Printer<double>::stream(s, indent + "  ", v.parking_stg1_steering_error);
    s << indent << "parking_stg2_steering_error: ";
    Printer<double>::stream(s, indent + "  ", v.parking_stg2_steering_error);
    s << indent << "begin_parking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.begin_parking);
    s << indent << "parking_stg1_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.parking_stg1_stop);
    s << indent << "parking_stg2_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.parking_stg2_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPICAM_NODE_MESSAGE_PARKING_H
