// Generated by gencpp from file raspicam_node/Perception_img.msg
// DO NOT EDIT!


#ifndef RASPICAM_NODE_MESSAGE_PERCEPTION_IMG_H
#define RASPICAM_NODE_MESSAGE_PERCEPTION_IMG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/CompressedImage.h>

namespace raspicam_node
{
template <class ContainerAllocator>
struct Perception_img_
{
  typedef Perception_img_<ContainerAllocator> Type;

  Perception_img_()
    : header()
    , undistorted_img()
    , bev_img()
    , mainlane_img()
    , parking_img()
    , tram_img()
    , background_img()
    , img7()
    , img8()  {
    }
  Perception_img_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , undistorted_img(_alloc)
    , bev_img(_alloc)
    , mainlane_img(_alloc)
    , parking_img(_alloc)
    , tram_img(_alloc)
    , background_img(_alloc)
    , img7(_alloc)
    , img8(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _undistorted_img_type;
  _undistorted_img_type undistorted_img;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _bev_img_type;
  _bev_img_type bev_img;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _mainlane_img_type;
  _mainlane_img_type mainlane_img;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _parking_img_type;
  _parking_img_type parking_img;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _tram_img_type;
  _tram_img_type tram_img;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _background_img_type;
  _background_img_type background_img;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _img7_type;
  _img7_type img7;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _img8_type;
  _img8_type img8;





  typedef boost::shared_ptr< ::raspicam_node::Perception_img_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspicam_node::Perception_img_<ContainerAllocator> const> ConstPtr;

}; // struct Perception_img_

typedef ::raspicam_node::Perception_img_<std::allocator<void> > Perception_img;

typedef boost::shared_ptr< ::raspicam_node::Perception_img > Perception_imgPtr;
typedef boost::shared_ptr< ::raspicam_node::Perception_img const> Perception_imgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspicam_node::Perception_img_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspicam_node::Perception_img_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace raspicam_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'raspicam_node': ['/home/corvin/catkin_ws/src/raspicam_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::raspicam_node::Perception_img_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspicam_node::Perception_img_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspicam_node::Perception_img_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspicam_node::Perception_img_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspicam_node::Perception_img_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspicam_node::Perception_img_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspicam_node::Perception_img_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a56b3e3562f70b07899255b3e4eb24a";
  }

  static const char* value(const ::raspicam_node::Perception_img_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a56b3e3562f70b0ULL;
  static const uint64_t static_value2 = 0x7899255b3e4eb24aULL;
};

template<class ContainerAllocator>
struct DataType< ::raspicam_node::Perception_img_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspicam_node/Perception_img";
  }

  static const char* value(const ::raspicam_node::Perception_img_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspicam_node::Perception_img_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message header\n\
# This message is only for all the imgs output by the synthetic segmentation \n\
Header header\n\
\n\
\n\
# IMG msg \n\
sensor_msgs/CompressedImage undistorted_img\n\
sensor_msgs/CompressedImage bev_img                # The bird's eye view image\n\
sensor_msgs/Image mainlane_img\n\
sensor_msgs/Image parking_img\n\
sensor_msgs/Image tram_img\n\
sensor_msgs/Image background_img\n\
sensor_msgs/CompressedImage img7\n\
sensor_msgs/CompressedImage img8\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/CompressedImage\n\
# This message contains a compressed image\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
\n\
string format        # Specifies the format of the data\n\
                     #   Acceptable values:\n\
                     #     jpeg, png\n\
uint8[] data         # Compressed image buffer\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
";
  }

  static const char* value(const ::raspicam_node::Perception_img_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspicam_node::Perception_img_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.undistorted_img);
      stream.next(m.bev_img);
      stream.next(m.mainlane_img);
      stream.next(m.parking_img);
      stream.next(m.tram_img);
      stream.next(m.background_img);
      stream.next(m.img7);
      stream.next(m.img8);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Perception_img_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspicam_node::Perception_img_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspicam_node::Perception_img_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "undistorted_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.undistorted_img);
    s << indent << "bev_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.bev_img);
    s << indent << "mainlane_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.mainlane_img);
    s << indent << "parking_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.parking_img);
    s << indent << "tram_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.tram_img);
    s << indent << "background_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.background_img);
    s << indent << "img7: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.img7);
    s << indent << "img8: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.img8);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPICAM_NODE_MESSAGE_PERCEPTION_IMG_H
