// Generated by gencpp from file low_level_control/low_level_msg.msg
// DO NOT EDIT!


#ifndef LOW_LEVEL_CONTROL_MESSAGE_LOW_LEVEL_MSG_H
#define LOW_LEVEL_CONTROL_MESSAGE_LOW_LEVEL_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace low_level_control
{
template <class ContainerAllocator>
struct low_level_msg_
{
  typedef low_level_msg_<ContainerAllocator> Type;

  low_level_msg_()
    : header()
    , linear_speed(0.0)
    , rotation_speed(0.0)
    , J_stage(0)
    , parking_stage(0)
    , urban_start_turning(false)  {
    }
  low_level_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , linear_speed(0.0)
    , rotation_speed(0.0)
    , J_stage(0)
    , parking_stage(0)
    , urban_start_turning(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _linear_speed_type;
  _linear_speed_type linear_speed;

   typedef double _rotation_speed_type;
  _rotation_speed_type rotation_speed;

   typedef int32_t _J_stage_type;
  _J_stage_type J_stage;

   typedef int32_t _parking_stage_type;
  _parking_stage_type parking_stage;

   typedef uint8_t _urban_start_turning_type;
  _urban_start_turning_type urban_start_turning;





  typedef boost::shared_ptr< ::low_level_control::low_level_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::low_level_control::low_level_msg_<ContainerAllocator> const> ConstPtr;

}; // struct low_level_msg_

typedef ::low_level_control::low_level_msg_<std::allocator<void> > low_level_msg;

typedef boost::shared_ptr< ::low_level_control::low_level_msg > low_level_msgPtr;
typedef boost::shared_ptr< ::low_level_control::low_level_msg const> low_level_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::low_level_control::low_level_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::low_level_control::low_level_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace low_level_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'low_level_control': ['/home/corvin/catkin_ws/src/low_level_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::low_level_control::low_level_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::low_level_control::low_level_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level_control::low_level_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level_control::low_level_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level_control::low_level_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level_control::low_level_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::low_level_control::low_level_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c762b1c31a1dd634c8be30cbcb06f431";
  }

  static const char* value(const ::low_level_control::low_level_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc762b1c31a1dd634ULL;
  static const uint64_t static_value2 = 0xc8be30cbcb06f431ULL;
};

template<class ContainerAllocator>
struct DataType< ::low_level_control::low_level_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "low_level_control/low_level_msg";
  }

  static const char* value(const ::low_level_control::low_level_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::low_level_control::low_level_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message header\n\
Header header\n\
\n\
# Vehicle States\n\
float64 linear_speed\n\
float64 rotation_speed\n\
\n\
int32 J_stage\n\
int32 parking_stage\n\
\n\
bool urban_start_turning\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::low_level_control::low_level_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::low_level_control::low_level_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.linear_speed);
      stream.next(m.rotation_speed);
      stream.next(m.J_stage);
      stream.next(m.parking_stage);
      stream.next(m.urban_start_turning);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct low_level_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::low_level_control::low_level_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::low_level_control::low_level_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "linear_speed: ";
    Printer<double>::stream(s, indent + "  ", v.linear_speed);
    s << indent << "rotation_speed: ";
    Printer<double>::stream(s, indent + "  ", v.rotation_speed);
    s << indent << "J_stage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.J_stage);
    s << indent << "parking_stage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.parking_stage);
    s << indent << "urban_start_turning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.urban_start_turning);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOW_LEVEL_CONTROL_MESSAGE_LOW_LEVEL_MSG_H
