# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from raspicam_node/Parking.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Parking(genpy.Message):
  _md5sum = "ed391e1436c52e7f07926b152c4f1a22"
  _type = "raspicam_node/Parking"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# Message header
Header header


# Numerical variables
float64 steering_error    # The steering angle error for lane keeping
float64 parking_stg1_steering_error
float64 parking_stg2_steering_error


# Bool signals 
bool begin_parking        # begin parking (J-shape)
bool parking_stg1_stop
bool parking_stg2_stop
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','steering_error','parking_stg1_steering_error','parking_stg2_steering_error','begin_parking','parking_stg1_stop','parking_stg2_stop']
  _slot_types = ['std_msgs/Header','float64','float64','float64','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,steering_error,parking_stg1_steering_error,parking_stg2_steering_error,begin_parking,parking_stg1_stop,parking_stg2_stop

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Parking, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.steering_error is None:
        self.steering_error = 0.
      if self.parking_stg1_steering_error is None:
        self.parking_stg1_steering_error = 0.
      if self.parking_stg2_steering_error is None:
        self.parking_stg2_steering_error = 0.
      if self.begin_parking is None:
        self.begin_parking = False
      if self.parking_stg1_stop is None:
        self.parking_stg1_stop = False
      if self.parking_stg2_stop is None:
        self.parking_stg2_stop = False
    else:
      self.header = std_msgs.msg.Header()
      self.steering_error = 0.
      self.parking_stg1_steering_error = 0.
      self.parking_stg2_steering_error = 0.
      self.begin_parking = False
      self.parking_stg1_stop = False
      self.parking_stg2_stop = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3d3B().pack(_x.steering_error, _x.parking_stg1_steering_error, _x.parking_stg2_steering_error, _x.begin_parking, _x.parking_stg1_stop, _x.parking_stg2_stop))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.steering_error, _x.parking_stg1_steering_error, _x.parking_stg2_steering_error, _x.begin_parking, _x.parking_stg1_stop, _x.parking_stg2_stop,) = _get_struct_3d3B().unpack(str[start:end])
      self.begin_parking = bool(self.begin_parking)
      self.parking_stg1_stop = bool(self.parking_stg1_stop)
      self.parking_stg2_stop = bool(self.parking_stg2_stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3d3B().pack(_x.steering_error, _x.parking_stg1_steering_error, _x.parking_stg2_steering_error, _x.begin_parking, _x.parking_stg1_stop, _x.parking_stg2_stop))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.steering_error, _x.parking_stg1_steering_error, _x.parking_stg2_steering_error, _x.begin_parking, _x.parking_stg1_stop, _x.parking_stg2_stop,) = _get_struct_3d3B().unpack(str[start:end])
      self.begin_parking = bool(self.begin_parking)
      self.parking_stg1_stop = bool(self.parking_stg1_stop)
      self.parking_stg2_stop = bool(self.parking_stg2_stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d3B = None
def _get_struct_3d3B():
    global _struct_3d3B
    if _struct_3d3B is None:
        _struct_3d3B = struct.Struct("<3d3B")
    return _struct_3d3B
